#Import dataset
dataset <- read.csv("C:/Users/ML/Dropbox/Work/Job Search/Potential Employers/Indeed/homework_data_set.csv")

#Number of leads is equal to number of rows in dataset
nleads <- nrow(dataset)

#Count number of leads in assigned and unassigned populations
table(dataset$assigned)

#Convert "NA" value in revenue to zero for upcoming analyses
dataset$revenue[is.na(dataset$revenue)]=0

#Avg of revenue by assigned group
avg_revenue <- as.numeric(aggregate(revenue~assigned,dataset,FUN=mean)[2][,1])
names(avg_revenue) <- c("Unassigned","Assigned")

barplot(avg_revenue,main="Average Revenue by assignment", xlab="Assignment", ylab="$ dollars")

#Subset by assignment
data_assigned <- dataset[dataset$assigned==1,]
data_unassigned <- dataset[dataset$assigned==0,]

#Calculate cumulative sums of revenue for subsets
data_assigned <- data_assigned[order(data_assigned$age),]
data_unassigned <- data_unassigned[order(data_unassigned$age),]
data_assigned$rev_cumsum <- cumsum(data_assigned$revenue)
data_unassigned$rev_cumsum <- cumsum(data_unassigned$revenue)
dataset <- dataset[order(dataset$age),]
dataset$rev_cumsum <- cumsum(dataset$revenue)

##Assess relationship between age and revenue
plot(dataset$age,dataset$rev_cumsum)

#Assess relationship between age and revenue in unassigned
plot(data_unassigned$age,data_unassigned$revenue)
plot(data_unassigned$age,data_unassigned$revenue,ylim=c(0,600000000),xlim=c(0,1500))
plot(data_unassigned$age,data_unassigned$rev_cumsum)

#Most revenue is generated close to the date the lead was created. Afterwards, the number of leads resulting in revenue decrease with age

#Assess relationship between age and revenue in assigned
plot(data_assigned$age,data_assigned$revenue)
plot(data_assigned$age,data_assigned$revenue,ylim=c(10000000,3000000000))
plot(data_assigned$age,data_assigned$rev_cumsum)

#Revenue is produced dependent upon the age of the lead up until 2000 days



#Advanced analysis: Leads created before assignment date are a special case. 
#plot by first_revenue_date

#Assess the revenue generated by date
dataset <- dataset[order(dataset$first_revenue_date),]
dataset$rev_cumsum <- cumsum(dataset$revenue)
plot(dataset$first_revenue_date,dataset$revenue)
plot(dataset$first_revenue_date,dataset$rev_cumsum)

data_unassigned <- data_unassigned[order(data_unassigned$first_revenue_date),]
data_unassigned$rev_cumsum <- cumsum(data_unassigned$revenue)
plot(data_unassigned$first_revenue_date,data_unassigned$rev_cumsum)


data_assigned <- data_assigned[order(data_assigned$first_revenue_date),]
data_assigned$rev_cumsum <- cumsum(data_assigned$revenue)

plot(dataset$first_revenue_date,dataset$rev_cumsum)
lines(data_unassigned$first_revenue_date,data_unassigned$rev_cumsum, col='red')
lines(data_assigned$first_revenue_date,data_assigned$rev_cumsum, col='blue')

#Use linear regression model to assess added revenue by assigning lead
rev_mod <- lm(dataset$revenue~dataset$assigned)
summary(rev_mod)
all_mod <- lm(dataset$revenue~dataset$advertiser_id+dataset$assigned+as.integer(dataset$date_assignment_starts)+as.integer(dataset$date_assignment_ends)+as.integer(dataset$first_revenue_date)+as.integer(dataset$date_created)+dataset$age+dataset$assign_days)
summary(all_mod)
